### PR TITLE
RAD-165: Separate TVAC and FPS Schemas from Main

### LINKED ISSUE #407: Standalone TVAC and FPS Schemas
_Issue [RAD-165](https://jira.stsci.edu/browse/RAD-165) was created on JIRA by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva):_

The current TVAC and FPS schemas reuse portions of the science data schemas. This is a problem because the science data schemas still change often and this breaks TVAC data definitions. By generating standalone schemas, not referencing existing science data tags this will be avoided.

### PR DESCRIPTION
**Pull request by PaulHuwe**
Resolves [RAD-165](https://jira.stsci.edu/browse/RAD-165)

Closes #407 

This PR creates a suite of separate TVAC and FPS schemas to freeze them and keep them separate from main development. NOTE: archive catalog targets need updating, which I will split out into another ticket.

**Checklist**
- [x] Schema changes discussed at RAD Review Board meeting
- [ ] Added entry in `CHANGES.rst` under the corresponding subsection
- [x] Updated relevant roman_datamodels utilities and tests
- [x] Passed romancal regression testing on Jenkins / PLWishMaster. Link: https://github.com/spacetelescope/roman_datamodels/pull/344/files

### CODE REVIEW

**Review by jbrookens — APPROVED** [review]
The only question I had was the archive catalog destinations being a superset, but I see you're handling those updates as a future ticket. No other concerns from me.

**Comment by nden** [comment]
Looks good to me.
For my understanding - since these files are stored in a different archive, is the `archive_catalog` section even needed?

**Comment by jbrookens** [comment]
> Looks good to me. For my understanding - since these files are stored in a different archive, is the `archive_catalog` section even needed?
Still needed.

**Comment by kdupriestsci** [comment]
It looks like there's a lot of duplicated data between the fps and tvac folders. Can any of those files be shared between the two?

I understand that you don't want to share with science data since the science schemas are in flux, but does that problem exist at the individual test level as well?

**Comment by kdupriestsci** [comment]
You've left references to ScienceRefData and GuideWindow tables in the tvac and fps files. We don't have ScienceRefData for RITA (it's stored in WFICommon.  We don't have GuideWindow for RITA (my understanding is we don't have GuideWindows for test data).

**Comment by PaulHuwe** [comment]
> It looks like there's a lot of duplicated data between the fps and tvac folders. Can any of those files be shared between the two?
> 
> I understand that you don't want to share with science data since the science schemas are in flux, but does that problem exist at the individual test level as well?

It was decided to freeze TVAC and FPS individually, which means we need to keep the duplicates.

**Comment by PaulHuwe** [comment]
> Will the RITA schemas always be isolated from the Roman schemas? If yes, maybe Tim @relaxing could make use of the archive_meta tag (currently set to None) to distinguish Roman from RITA?

This sounds good to me.. do you want to discuss it at a RAD meeting, or just have @relaxing implement it as it is an archive only keyword?

**Review by nden — APPROVED** [review]

**Pull request merged**
