### PR TITLE
RAD-71 Move archive information to be in tags

### PR DESCRIPTION
**Pull request by WilliamJamieson**
Moves archive related information directly into a tagged object for easier retrieval by ASDF.

### CODE REVIEW

**Review by nden — APPROVED** [review]
LGTM

**Review by perrygreenfield — APPROVED** [review]
Also LGTM

**Comment by WilliamJamieson** [comment]
I'm leaving this in draft form until the changes to roman_datamodels are ready.

**Review by gardner358 — APPROVED** [review]

**Review by PaulHuwe — APPROVED** [review]
LGTM

**Review by kdupriestsci — COMMENTED** [review]
LGTM

**Pull request merged**
