### PR TITLE
Add method to generate list of all archive_catalog destinations

### PR DESCRIPTION
**Pull request by WilliamJamieson**
Adds method to generate a list of all `archive_catalog` destinations.

### CODE REVIEW

**Comment by WilliamJamieson** [comment]
> Would it be helpful to have the yaml keyword (possibly with path) associated with each archive_catalog entry? @ddavis-stsci @kdupriestsci

Getting anymore then the immediate keyword is impossible to get without processing the schemas through ASDF (or doing the equivalent with ad hoc logic). So this is outside the scope of what is possible with these changes.

It should be possible to get the immediate keyword; however, it will impose outside limitations on how archive_catalog values are structured (namely no internal schema logic in relation to the archive metadata) and that all  archive_catalog metadata entries are wrapped by a keyword. It will also require another layer of processing to deduce what this keyword is, which will significantly increase the code complexity.

**Review by PaulHuwe — APPROVED** [review]
LGTM

**Review by ddavis-stsci — APPROVED** [review]
Looks fine, I can run it without issues.

**Review by kdupriestsci — APPROVED** [review]
I'm not sure what this will be used for but it looks good to me.

**Comment by WilliamJamieson** [comment]
> I'm not sure what this will be used for but it looks good to me.

This is the initial attempt to get you something that can read all the archive end-points from `rad`. So is this what you described needing last week?

**Comment by kdupriestsci** [comment]
> > I'm not sure what this will be used for but it looks good to me.
> 
> This is the initial attempt to get you something that can read all the archive end-points from `rad`. So is this what you described needing last week?

This isn't quite what I'm looking for.  Please see the email I sent.

**Review by kdupriestsci — APPROVED** [review]

**Pull request closed without merging**
