### PR TITLE
Added support for GLS Ramp fitting.

### PR DESCRIPTION
**Pull request by PaulHuwe**
This PR is to add GLS Ramp fitting schema.

Tests: Passes standard tests

Docs: Unneeded

Ticket #30

### CODE REVIEW

**Review by ddavis-stsci — APPROVED** [review]
Question: Do we also need to save the weights and noise levels used in the fitting? If we do we can always write a ticket to add them.

**Comment by PaulHuwe** [comment]
This depends on Issue #24

**Comment by nden** [comment]
We are not supporting gls ramp fitting for now. Consider closing this ticket and reopen if needed in the future.

**Comment by PaulHuwe** [comment]
Closing this as it is unneeded.

**Pull request closed without merging**
