### PR TITLE
RAD-139: Add Members Keyword to Resample Schema

### LINKED ISSUE #340: Add Members Keyword to Resample Schema
_Issue [RAD-139](https://jira.stsci.edu/browse/RAD-139) was created on JIRA by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe):_

The members keyword needs to be added to the resample schema. It is an array of strings.

### PR DESCRIPTION
**Pull request by PaulHuwe**
Resolves [RAD-139](https://jira.stsci.edu/browse/RAD-139)

Closes #340 

This PR adds the members keyword to the resample schema.

**Checklist**
- [ ] Schema changes discussed at RAD Review Board meeting
- [x] Added entry in `CHANGES.rst` under the corresponding subsection
- [x] Updated relevant roman_datamodels utilities and tests
- [x] Passed romancal regression testing on Jenkins / PLWishMaster. Link: https://plwishmaster.stsci.edu:8081/job/RT/job/romancal/692/

### CODE REVIEW

**Review by kdupriestsci — APPROVED** [review]

**Comment by schlafly** [comment]
Do we expect the members to already be included as individual_image_meta.basic.filename?  It is good to include this somewhere, and we aren't currently populating individual_image_meta.basic.filename, but once is probably enough?

**Review by ddavis-stsci — APPROVED** [review]
Looks good

**Comment by PaulHuwe** [comment]
> Do we expect the members to already be included as individual_image_meta.basic.filename? It is good to include this somewhere, and we aren't currently populating individual_image_meta.basic.filename, but once is probably enough?

Yes, I would expect this information to be in `individual_image_meta.basic['filename']` (`basic` is a table). The reason for this ticket is that romancal does set this keyword value (e.g. https://github.com/spacetelescope/romancal/blob/main/romancal/resample/resample.py#L311), so it should be added to the schema. I have not gone through romancal to see if removing that entirely would affect other steps or not.

**Comment by schlafly** [comment]
Okay, fine to duplicate this.

**Pull request merged**
